mysite/blog/urls.py
from django.urls import path 
from . import views 

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('search/', views.post_search, name='post_search'),
]
    

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


# Комментарии к постам
class Comment(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField(max_length=100)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f'Комментарий от {self.name} к {self.post}'    


# Менеджер опубликованных постов
class PublishManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()\
                .filter(status=Post.Status.PUBLISHED)


# Посты
class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=255)
    slug =  models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, 
                               on_delete=models.CASCADE, 
                               related_name='blog_post')

    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices,
                              default=Status.DRAFT)
    tags = TaggableManager()

    objects = models.Manager()
    published = PublishManager()


    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                                 self.publish.month,
                                                 self.publish.day,
                                                 self.slug])

    def __str__(self):
        return self.title

mysite/blog/forms.py
from django import forms 
from .models import Comment


class EmailPostForms(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']
        

class SearchForm(forms.Form):
    query = forms.CharField(label='Запрос')
    

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForms, CommentForm, SearchForm
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, \
                                           SearchQuery, SearchRank, \
                                           TrigramSimilarity


def post_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', weight='A') + \
                            SearchVector('body', weight='B')
            search_query = SearchQuery(query, config='russian')
            results = Post.published.annotate(
                similarity=TrigramSimilarity('title', query)
            ).filter(similarity__gte=0.1).order_by('-similarity')

    return render(request,
                 'blog/post/search.html',
                 {'form': form,
                 'query': query,
                 'results': results
                 })    



def post_list(request, tag_slug=None):
    post_list = Post.objects.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    # Постраничная разбивка с 3 постами на страницу
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        # Если page_number не целое число выдать первую страницу    
        posts = paginator.page(1)    
    except EmptyPage:
        # Если page_number находится вне диапазона, то
        # выдать последнюю страницу
        posts = paginator.page(paginator.num_pages)    
    return render(request, 'blog/post/list.html', {'posts': posts,
                                                   'tag': tag})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post,
                             id=post_id,
                             status=Post.Status.PUBLISHED)
    comment = None
    # Комментарий был отправлен
    form = CommentForm(data=request.POST)
    if form.is_valid():
        # Создать обьект класса Comment, не сохраняя его в базе данных
        comment = form.save(commit=False)
        # Назначить пост комментарию
        comment.post = post
        # Сохранить комментарий в базе данных
        comment.save()
    return render(request, 'blog/post/comment.html',
                  {'post': post,
                   'form': form,
                   'comment': comment})    



def post_share(request, post_id):
    #Извлечь пост по индитификатору  
    post = get_object_or_404(Post,
                            id=post_id,
                            status=Post.Status.PUBLISHED)
    sent = False

    if request.method == 'POST':
        #Форма отправлена на обработку
        form = EmailPostForms(request.POST)
        if form.is_valid():
            #Поля формы прошли валидацию
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f'{cd["name"]} рекомендуем тебе прочитать'\
                      f'{post.title}'
            message = f'Читатйте {post.title} в {post_url}\n\n'\
                      f'{cd["name"]} комментарии: {cd["comments"]}'
            send_mail(subject, message, 'nikitamikhailov2392@gmail.com', [cd['to']])
            sent = True

    else:
        form = EmailPostForms()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})            
           
class PostListView(ListView):
    queryset = Post.objects.all()
    content_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, 
                            status=Post.Status.PUBLISHED,
                            slug=post,
                            publish__year=year,
                            publish__month=month,
                            publish__day=day)  
    
    # Список активных комментариев к этому посту 
    comments = post.comments.filter(active =True) 
    # Форма для комментария пользователями
    form = CommentForm()
    # Список схожих постов
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids)\
                                  .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                                 .order_by('same_tags', '-publish')[:4]
    
    return render(request,
                  'blog/post/detail.html',
                   {'post': post,
                    'comments': comments,
                    'form': form,
                    'similar_posts': similar_posts})

mysite/blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">
</head>
<body>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <div id="sidebar">
        <h2>Мой блог</h2>
        <p>Это мой блог.
            Было написано {% total_posts %} постов.
        </p>
        <h3>Последние посты</h3>
        {% show_latest_posts 3 %}
        <h3>Последние комментарии</h3>
        {% get_most_commented_posts as most_commented_posts %}
        <ul>
            {% for post in most_commented_posts %}
            <li>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

mysite/blog/templates/blog/post/comment.html
{% extends 'blog/base.html' %}

{% block title %}Добавление комментария{% endblock %}

{% block content %}
    {% if comment %}
        <h2>Ваш комментарий был добавлен</h2>
        <p><a href="{{ post.get_absolute_url }}">Вернуться к посту</a></p>
    {% else %}
        {% include 'blog/post/includes/comment_form.html' %}
    {% endif %}
{% endblock %}

mysite/blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<h1>{{ post.title }}</h1>
<p class="date">
    Публикация {{ post.publish }} от {{ post.author }}
</p>
{{ post.body|markdown }}
<p>
    <a href="{% url 'blog:post_share' post.id %}">
        Поделиться этим постом  
    </a>
</p>  
<h2>Похожие посты</h2>
{% for post in similar_posts %}
<p>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
</p>
{% empty %}
Нет похожих постов
{% endfor %}

{% with comments.count as total_comments %}
    <h2>
        {{ total_comments }} comment{{ total_comments|pluralize }}
    </h2>
{% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Комментарий {{ forloop.counter }} от {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>Комментарии отсутствуют</p>    
    {% endfor %}    
    <a href="{% url 'blog:post_list' %}">Вернуться на главную</a>
    {% include 'blog/post/includes/comment_form.html' %}
{% endblock %}

mysite/blog/templates/blog/post/includes/comment_form.html
<h2> Добавлен новый комментарий</h2>
<form action="{% url 'blog:post_comment' post.id %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }} 
    <p><input type="submit" value="Добавление комментария"></p>
</form>

mysite/blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

mysite/blog/templates/blog/post/list.html
{%  extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}Мой блог{% endblock %}

{% block content %}
    <h1>Мой блог</h1>
    {% if tag %}
        <h2>Посты с тегами: '{{ tag.name }}'</h2>
    {% endif %}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h2>
        <p class="tags">
            Теги: 
            {% for tag in post.tags.all %}
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                    {{ tag.name }}
                </a>
                {% if not forllop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p class="date">
            Публикация {{ post.publish }} от {{ post.author }}
        </p>
        {{ post.body|markdown|truncatewords_html:30 }}
    {% endfor %}
    {% include 'pagination.html' with page=posts %}
{% endblock %}

mysite/blog/templates/blog/post/search.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}Поиск{% endblock %}

{% block content %}
    {% if query %}
        <h1>Пост содержит "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
            {% if total_results > 1 %}
                Найдено {{ total_results }} результатов 
            {% else %}
                Найден {{ total_results }} результат
            {% endif %}    
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </h4>
            {{ post.body|markdown|truncatewords_html:12 }}
            {% empty %}
            <p>Отсутсвует результат по данному запросу</p>
            {% endfor %}
            <p><a href="{% url 'blog:post_search' %}">Найти снова</a></p>
        {% else %}    
        <h1>Поиск постов</h1>
        <form method="get">
            {{ form.as_p }}
            <input type="submit" value="Поиск">
        </form>
    {% endif %}
{% endblock %}

mysite/blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block title %}Поделиться постом{% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail успешно отправлено</h1>
        <p>
            "{{ post.title }}" было успешно отправлено на {{ form.cleaned_data.to }}.
        </p>
    {% else %}
        <h1>
            Поделиться "{{ post.title }} отправив на e-mail"
        </h1>
        <form method="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Отправить на e-mail">
        </form>
    {% endif %}
{% endblock %}

mysite/blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Предыдущая</a>
        {% endif %}
        <span class="current">
            Страница {{ page.number }} из {{ page.paginator.num_pages }}
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Следующая</a>
        {% endif %}
    </span>
</div>